language: node_js
node_js:
  - "10.16.3"
  - "12.10.0"
sudo: false
addons:
  firefox: "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
env:
  - CXX=g++
notifications:
  email:
    on_success: never
